---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.96.0.10  # Your cluster's DNS service IP
        searches:
          - mongodb.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
          - name: single-request-reopen
            value: ""
      initContainers:
        - name: init-dns-check
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup kubernetes.default.svc.cluster.local; do echo waiting for DNS; sleep 2; done;']
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
          command: ["mongod"]
          args: ["--config", "/etc/mongod.conf"]
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: mongodb-data
          emptyDir: {}
        - name: mongodb-config
          configMap:
            name: mongodb-config