# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsaas-userportal.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "vsaas-userportal.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}