apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods verified
           ttl 30
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4 {
           max_concurrent 1000
           force_tcp
        }
        cache 30
        loop
        reload
        loadbalance
    }
    cluster.local:53 {
        errors
        cache 30
        kubernetes {
           pods verified
           ttl 30
        }
    }
