apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mongo-auth-password: {{ .Values.secrets.mongoAuthPassword }}
  redis-password: {{ .Values.secrets.redisPassword }}
  rcs-db-password: {{ .Values.secrets.rcsDbPassword }}
  COM_VTPL_MAIL_SENDER_MAIL_PASSWORD: {{ .Values.secrets.mailSenderPassword }}
  VTPL_INSIGHTS_DB_PASSWORD: {{ .Values.secrets.insightsDbPassword }}
