# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: vsaas-metallb
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: metallb
    meta.helm.sh/release-namespace: vsaas-metallb
spec:
  addresses:
  - 172.235.26.240/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: vsaas-metallb
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: metallb
    meta.helm.sh/release-namespace: vsaas-metallb
spec:
  ipAddressPools:
  - default-pool