# nginx-controller/templates/prometheusrule.yaml
{{- if .Values.controller.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.controller.metrics.prometheusRule.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.controller.metrics.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: nginx.ingress.rules
      rules:
        {{- with .Values.controller.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}