apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsaas-adminportal.fullname" . }}-service
  labels:
    {{- include "vsaas-adminportal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "vsaas-adminportal.name" . }}