apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongo-root-username: {{ .Values.mongodb.auth.username }}
  mongo-root-password: {{ .Values.mongodb.auth.password }}