# templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mongodb.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongodb.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.mongodb.nodeSelector.hostname }}
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        imagePullPolicy: {{ .Values.mongodb.imagePullPolicy }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb.fullname" . }}-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb.fullname" . }}-secret
              key: mongo-root-password
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ include "mongodb.fullname" . }}-pvc
      - name: mongodb-config
        configMap:
          name: {{ include "mongodb.fullname" . }}-config
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: {{ .Release.Name }}
#   namespace: {{ .Values.namespace }}
#   labels:
#     {{- include "mongodb.labels" . | nindent 4 }}
# spec:
#   serviceName: {{ .Release.Name }}
#   replicas: 1
#   selector:
#     matchLabels:
#       app: {{ .Release.Name }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Release.Name }}
#     spec:
#       nodeSelector:
#         kubernetes.io/hostname: {{ .Values.mongodb.nodeSelector.hostname }}
#       containers:
#       - name: mongodb
#         image: {{ .Values.mongodb.image }}
#         imagePullPolicy: {{ .Values.mongodb.imagePullPolicy }}
#         env:
#         - name: MONGO_INITDB_ROOT_USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: {{ .Release.Name }}-secret
#               key: mongo-root-username
#         - name: MONGO_INITDB_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: {{ .Release.Name }}-secret
#               key: mongo-root-password
#         ports:
#         - containerPort: 27017
#         volumeMounts:
#         - name: mongodb-data
#           mountPath: /data/db
#         - name: mongodb-config
#           mountPath: /etc/mongod.conf
#           subPath: mongod.conf
#       volumes:
#       - name: mongodb-data
#         persistentVolumeClaim:
#           claimName: {{ .Release.Name }}-pvc
#       - name: mongodb-config
#         configMap:
#           name: {{ .Release.Name }}-config