apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vsaas-rcshandler.fullname" . }}-config
  labels:
    {{- include "vsaas-rcshandler.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}