apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "vsaas-rcshandler.labels" . | nindent 4 }}
type: Opaque
stringData:
  rcs-db-password: {{ .Values.secrets.rcsDbPassword }}